baseURL = "/"
languageode = "es"
theme = "hugo-notepadium"
defaultContentLanguage = "es"

enableRobotsTXT = true

# Enable Disqus
# disqusShortname = "elrobotistaDisqus"

# Google Analytics
googleAnalytics = "UA-96903957-1"

[author]
  name = "El Robotista"
  homepage = "https://elrobotista.com"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "dark"
dateFormat = "Monday, January 2, 2006"
logo = "img/ElRobotista.png"
#slogan = "Un blog de robótica"
license = ""
fullRss = false
description ="Un blog de Robótica"
images = ["/ElRobotistaLab.jpg"]
gitURL = "https://github.com/elrobotista/"

[params.comments]
enable = true

[params.math]
enable = true
use = "mathjax"

[params.syntax]
use = "hljs"
theme = "gruvbox-light"
darkTheme = "gruvbox-dark"

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

[params.nav]
showCategories = false
showTags = false

[[params.nav.custom]]
title = "Blog"
url = "/"

[[params.nav.custom]]
title = "Nosotros"
url = "/about/"

[[params.nav.custom]]
title = "Autores"
url = "/authors/"
